version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          branch_pattern: main|^hotfix\/.+$
          channel: test
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":rocket: circleci-slack start deploying to QA"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "@here"
                    }
                  ]
                }
              ]
            }

workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
