version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          branch_pattern: main|^hotfix\/.+$
          channel: test
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here *circleci-slack* start deploying to QA"
                  }
                }
              ]
            }

workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
